name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TZ: Asia/Jakarta
  ghuser_name: ${{ secrets.GHUSER_NAME }}
  ghuser_email: ${{ secrets.GHUSER_EMAIL }}
  llvm_url: https://github.com/llvm/llvm-project.git

jobs:
  clone_project:
    name: Cloning Project (llvm source)
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'build-datestamp')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone LLVM project
        run: git clone --single-branch "${{ env.llvm_url }}" -b main src/llvm-project --depth=1

  build_profile:
    name: Build LLVM (profile)
    runs-on: ubuntu-latest
    needs: clone_project
    if: "!contains(github.event.head_commit.message, 'build-datestamp')"
    steps:
      - name: Setup environment
        run: |
          ./tc_scripts/init.sh profile
      - name: Cleanup instrumented build files
        run: find build/llvm/instrumented -type f ! -name 'profdata.prof' -delete

  build_final:
    name: Build LLVM (final)
    runs-on: ubuntu-latest
    needs: build_profile
    if: "!contains(github.event.head_commit.message, 'build-datestamp')"
    steps:
      - name: Setup environment
        run: ./tc_scripts/init.sh final
